POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "blog with user test",
  "author": "blog with user author",
  "url": "http://testurl.com",
  "likes": 200,
  "userId": "62fafe1e1710476639b2ee97"
}