#Get all blogs
GET http://localhost:3003/api/blogs
Authorization: bearer 
###
# Get one blog
GET http://localhost:3003/api/blogs/62f1725e5a1328324533143df58

###
# Add a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer 

{
  "title": "sebaperi title",
  "author": "sebaperi author",
  "url": "http://testurl.com",
  "likes": 1225
}

###
# Remove on blog
DELETE http://localhost:3003/api/blogs/62fe63b71ae4b7abc8a8edf8
Authorization: bearer 
###
# Update a blog

PUT http://localhost:3003/api/blogs/62f81780e48536020e765102
Content-Type: application/json
Authorization: bearer 

{
  "title": "updated test",
  "author": "EL test",
  "url": "httpsss",
  "likes": 35
}


